<?xml version="1.0" encoding="UTF-8"?>
<CustomObjectTranslation xmlns="http://soap.sforce.com/2006/04/metadata">
    <fields>
        <help><!-- If any exception was thrown during the Apex execution to show this component, the message is shown here --></help>
        <label><!-- Exception Message --></label>
        <name>ltngMap__Exception_Message__c</name>
    </fields>
    <fields>
        <help><!-- If any exception was thrown in Apex during the course of this execution, the type of exception thrown is shown here --></help>
        <label><!-- Exception Type --></label>
        <name>ltngMap__Exception_Type__c</name>
    </fields>
    <fields>
        <help><!-- Shows the fields the user had no access to when attempting to view the recordMap component --></help>
        <label><!-- Inaccessible Fields --></label>
        <name>ltngMap__Inaccessible_Fields__c</name>
    </fields>
    <fields>
        <help><!-- Shows the attempted Apex query when a user loads the recordMap component --></help>
        <label><!-- Mapping Query --></label>
        <name>ltngMap__Mapping_Query__c</name>
    </fields>
    <fields>
        <help><!-- The name of the object on which this error occurred --></help>
        <label><!-- Object Name --></label>
        <name>ltngMap__Object_Name__c</name>
    </fields>
    <fields>
        <help><!-- The record where this error occurred --></help>
        <label><!-- Record ID --></label>
        <name>ltngMap__Record_ID__c</name>
    </fields>
    <layouts>
        <layout>Mapping Error Layout</layout>
        <sections>
            <label><!-- Custom Links --></label>
            <section>Custom Links</section>
        </sections>
        <sections>
            <label><!-- Error Details --></label>
            <section>Error Details</section>
        </sections>
        <sections>
            <label><!-- Exception Details --></label>
            <section>Exception Details</section>
        </sections>
    </layouts>
</CustomObjectTranslation>
